### ISSUE TITLE
Path of Executable JAR listed in README seems incorrect 

### ISSUE THREAD

**Issue by shawnshaligram** [gojuno/swarmer#17]
The curl command listed  
`curl --fail --location https://jcenter.bintray.com/com/gojuno/swarmer/swarmer/${SWARMER_VERSION}/swarmer-${SWARMER_VERSION}.jar --output /tmp/swarmer.jar`will download `swarmer.jar` but the invocation example says `java -jar swarmer-latest-version.jar`

Shouldn't this be `java -jar swarmer.jar` ? otherwise i get error `Error: Unable to access jarfile /tmp/swarmer-latest-version.jar`

**Comment by ming13** [comment]
Probably just a copy-paste issue from our scripts or something. Thanks!

**Comment by artem-zinnatullin** [comment]
You should launch file with exactly the same name as downloaded, `curl` and run examples are just not using the same file name, we'll fix that thanks!

@ming13 it's not a copy-paste issue, `swarmer-latest-version.jar` was a hint to make sure users pay attention to the version of swarmer they download/work with, for instance artifact on Jcenter does have version in name `swarmer-${SWARMER_VERSION}.jar`.

However since now we provide `curl` sample, we probably need to change file name in examples to just `swarmer.jar`
